### ISSUE TITLE
Enhance error output for SessionRqstError with AOS HTTP API errors

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#13]
Please add the HTTP API error information to the SessionRqstError exception messaging.
This will help rapidly troubleshoot issues posting to the blueprint which may be very specific to back-end semantic validation.
An example:

```
class SessionRqstError(SessionError):
    def __init__(self, resp, message=None):
        self.resp = resp
	text = resp.text
	code = resp.status_code
        super(SessionRqstError, self).__init__('%s - %d:%s' % (message, code, text))
```

**Comment by jeremyschulman** [comment]
@jpsenior - great suggestion, thank you!  I'll roll this into the next spin.

**Comment by jeremyschulman** [comment]
working on this now, here is sample output for new exception:

````python
>>> aos = Session('aos-server')
>>> aos.login()
>>> 
>>> 
>>> aos.IpPools.names
[u'Switches-IpAddrs', u'Servers-IpAddrs']
>>> this = aos.IpPools['this']
>>> this.write('foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/collection_item.py", line 147, in write
    return self.create()
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/collection_item.py", line 202, in create
    resp=got)
apstra.aosom.exc.SessionRqstError: 422:{"errors": {"_schema": ["Invalid input type."]}} - unable to create: UNPROCESSABLE ENTITY
````

this OK?

**Comment by jpsenior** [comment]
Yes this is great!
