### ISSUE TITLE
Better exception message when using a blueprint that does not exist

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#18]
We get a generic requests.exceptions.MissingSchema error when an invalid blueprint is used.

A blueprint object is created with a name, value, and null ID.

Later, when trying to use this blueprint to query for slots, we get an HTTP requests.exception.MissingSchema error because the API URL Does not exist for this particular resource.

This might be more appropriate for an AccessValueError
```
from apstra.aosom.session import Session
aos = Session('192.168.59.250')

aos.login()

bp = aos.Blueprints['does-not-exist']
print bp
print bp.exists
print bp.params.names

```
A json bp is printed (interesting)
`
{
   "name": "does-not-exist", 
   "value": null, 
   "id": null
}
False

/home/jp/apstra/aos-pyez/env/bin/python /home/jp/apstra/aos-pyez/test.py
Traceback (most recent call last):
  File "/home/jp/apstra/aos-pyez/test.py", line 9, in <module>
    print bp.params.names
  File "/home/jp/apstra/aos-pyez/pylib/apstra/aosom/amods/blueprints.py", line 115, in names
    self.digest()
  File "/home/jp/apstra/aos-pyez/pylib/apstra/aosom/amods/blueprints.py", line 120, in digest
    got = requests.get("%s/slots" % self.blueprint.url, headers=self.api.headers)
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/models.py", line 366, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None/slots': No schema supplied. Perhaps you meant http://None/slots?
`

**Comment by jeremyschulman** [comment]
thank you.  I am going to mark this as a bug.  if the programmer is attempting to use aspects of a blueprint, and it doesn't exist, it should indicate an exception/error and not behave as you see it now,

**Comment by jpsenior** [comment]
I have a fix coming in in a flash.

**Comment by jeremyschulman** [comment]
the matter of how the aos-pyez should report on the programmer's attempt to access something that does not exist it much broader than this particular use case.  So I am going to try to find the best place to fix this issue across the board if possible.  working on this now.

**Comment by jeremyschulman** [comment]
creating a new exception called NoExistsError to make a specific class for these use-cases.

**Comment by jeremyschulman** [comment]
here is a working example:
````python
>>> from apstra.aosom.session import *
>>> aos = Session('aos-server')
>>> aos.login()
>>> 
>>> 
>>> this = aos.IpPools['nope']
>>> this.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/collection_item.py", line 171, in read
    got = requests.get(self.url, headers=self.api.headers)
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/collection_item.py", line 82, in url
    (self.name, self.collection.url))
apstra.aosom.exc.NoExistsError: name=nope, collection=http://aos-server:8888/api/resources/ip-pools
````

**Comment by jeremyschulman** [comment]
for your specific use-case, it would manifest like:

````python
>>> this.params.names
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/session_modules/blueprints.py", line 116, in names
    self.digest()
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/session_modules/blueprints.py", line 121, in digest
    got = requests.get("%s/slots" % self.blueprint.url, headers=self.api.headers)
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/collection_item.py", line 82, in url
    (self.name, self.collection.url))
apstra.aosom.exc.NoExistsError: name=nono, collection=http://aos-server:8888/api/blueprints
````

**Comment by jeremyschulman** [comment]
@jpsenior - please let me know if this is what you think would be good.

**Comment by jpsenior** [comment]
Ah, i like this fix much better than what I came up with, much more general usage.
