### ISSUE TITLE
aos.CollectionItem.create doesn't check for duplicates if instance name doesn't exist

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#22]
If I pass an arbitrary value to aso.CollectionItem[value] that does not represent an existing value of the same display_name, I can create duplicates.

```
>>> aos.AsnPools['Private'].value
{u'status': u'not_in_use', u'display_name': u'Private', u'tags': [], u'created_at': u'2016-12-14T15:15:55.661291Z', u'last_modified_at': u'2016-12-14T15:15:55.661291Z', u'ranges': [{u'status': u'pool_element_available', u'last': 65535, u'first': 65412}], u'id': u'7dcc15b2-4b6b-4979-9fff-059fd6ea8ec8'}


>>> aos.AsnPools['foobar'].create(aos.AsnPools['Private'].value)
True
>>> aos.AsnPools['foobar'].create(aos.AsnPools['Private'].value)
True
>>> aos.AsnPools.digest()
...

>>> aos.AsnPools.names

[u'Private', u'Private', u'Private']

```

Expected:
```
>>> aos.AsnPools['Private'].create(aos.AsnPools['Private'].value)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/jp/apstra/aos-pyez/pylib/apstra/aosom/collection.py", line 278, in create
    raise SessionError(message='cannot create, already exists')
SessionError: cannot create, already exists
```

Noting that aos.AsnPools.digest() does update the cache, but since 'foobar' doesn't exist as a display_name this will persist

**Comment by jeremyschulman** [comment]
@jpsenior - thank you.  I will mark this as a bug since it is the Programmer's expectation that duplication names should not be allowed via aos-pyez.

**Comment by jeremyschulman** [comment]
will also create a new Exception specific for this issue per @jpsenior #27

**Comment by jeremyschulman** [comment]
new exception is called `DuplicateError`
