### ISSUE TITLE
MissingSchema error if not logged in

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#35]
We get an HTTP error and not an AOS session error when we try to use a collection without being logged in.
Ran into this when misusing interactive python cli for some debugging.  Was temporarily misleading, because the http URL at least should have included '192.168.59.250' in the exception - interesting :)

```
>>> from apstra.aosom.session import Session
>>> aos = Session('192.168.59.250')
>>> aos.Blueprints
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/jp/apstra/aos-pyez/pylib/apstra/aosom/collection.py", line 296, in __str__
    'item-names': self.names
  File "/home/jp/apstra/aos-pyez/pylib/apstra/aosom/collection.py", line 116, in names
    self.digest()
  File "/home/jp/apstra/aos-pyez/pylib/apstra/aosom/collection.py", line 148, in digest
    got = requests.get(self.url, headers=self.api.headers)
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/home/jp/apstra/aos-pyez/env/local/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/models.py", line 366, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'None/blueprints': No schema supplied. Perhaps you meant http://None/blueprints?
```
Example fix:
```
from apstra.aosom.exc import SessionRqstError, AccessValueError, LoginError
def digest(self):
        if not self.api.headers:
            raise LoginError('No API headers available - did you remember to login?')
```

Should give a better exception to handle usage of aos-pyez if a user does things like:

```
>>> from apstra.aosom.session import Session
>>> aos = Session()
>>> aos.Blueprints
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/jp/apstra/aos-pyez/pylib/apstra/aosom/collection.py", line 298, in __str__
    'item-names': self.names
  File "/home/jp/apstra/aos-pyez/pylib/apstra/aosom/collection.py", line 116, in names
    self.digest()
  File "/home/jp/apstra/aos-pyez/pylib/apstra/aosom/collection.py", line 149, in digest
    raise LoginError('No API headers available - did you remember to .login() ?')
LoginError: No API headers available - did you remember to login?

**Comment by jeremyschulman** [comment]
@jpsenior - I'll fix in accordance to the architecture.  thank you.

**Comment by jeremyschulman** [comment]
Adding a new exception called `NoLoginError`.  Example:

````python
>>> from apstra.aosom.session import *
>>> aos = Session('aos-server')
>>> aos.Blueprints
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/dynmodldr.py", line 50, in __getattr__
    setattr(self, amod_name, cls(owner=self))
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/collection.py", line 100, in __init__
    self.url = "{api}/{uri}".format(api=owner.url, uri=self.__class__.RESOURCE_URI)
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/session.py", line 137, in url
    "not logged into server '{}:{}'".format(self.server, self.port))
apstra.aosom.exc.NoLoginError: not logged into server 'aos-server:8888'
````
