### ISSUE TITLE
Session.api.resume() does not check provided values

### ISSUE THREAD

**Issue by jeremyschulman** [Apstra/aos-pyez#44]
A User can attempt to "resume" an API session by providing a providing the prior url and headers value.  But the aos-pyez library does not take any action to verify that these values are good at that time.  Rather (presently), the User will retrieve an exception if they later attempt to use the API (i.e. authentication error if the token is bad/stale).

This issue tracks the need for the aos-api to take some action to "validate" the provided url/headers at the time the User calls the resume() method.

cc/ @dgarros

**Comment by jeremyschulman** [comment]
output from testing:
`````python
>>> from apstra.aosom.session import *
>>> aos = Session()
>>> aos.api.resume('http://aos-server:8888', {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/session.py", line 96, in resume
    message='missing "/api" in URL: [{}]'.format(url))
apstra.aosom.exc.LoginError: missing "/api" in URL: [http://aos-server:8888]
>>> aos.api.resume('http://aos-server:8888/api', {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/session.py", line 117, in resume
    raise LoginAuthError()
apstra.aosom.exc.LoginAuthError: AOS-server invalid auth credentials
>>> aos.api.resume('http://aos-server1:8888/api', {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeremy/Projects/aos-pyez/pylib/apstra/aosom/session.py", line 105, in resume
    message="Trying URL: [{}]".format(url))
apstra.aosom.exc.LoginServerUnreachableError: Trying URL: [http://aos-server1:8888/api]
>>> 
`````
