### ISSUE TITLE
Getting an error when trying to delete LogicalDevice_item

### ISSUE THREAD

**Issue by dgarros** [Apstra/aos-pyez#55]
I'm facing an issue that I can't explain right now, I'm opening this issue for tracking and in case someone has an idea of what the issue might be.  

As part of the development of the ansible module `aos_logical_device`, I need to delete an existing Logical Device.

When I do it in manually with Python, it's working good, but when I do it inside the ansible module i get a very strange error. see below.

The object is retrieve using .find() in the ansible module and I checked that the object returned is valid. 

```
TASK [SETUP 200 - Cleanup existing server] *************************************************************************************************************************************
task path: /Users/damien/projects/aos-ansible/tests/pb.aos_logical_device.yaml:106
Using module file /Users/damien/projects/ansible/lib/ansible/modules/network/aos/aos_logical_device.py
<aos> ESTABLISH LOCAL CONNECTION FOR USER: damien
<aos> EXEC /bin/sh -c 'echo ~ && sleep 0'
<aos> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/damien/.ansible/tmp/ansible-tmp-1486431728.36-240467798124239 `" && echo ansible-tmp-1486431728.36-240467798124239="` echo /Users/damien/.ansible/tmp/ansible-tmp-1486431728.36-240467798124239 `" ) && sleep 0'
<aos> PUT /var/folders/vn/2sns6pr17wzdszrwdq79x3th0000gn/T/tmpbFK72g TO /Users/damien/.ansible/tmp/ansible-tmp-1486431728.36-240467798124239/aos_logical_device.py
<aos> EXEC /bin/sh -c 'chmod u+x /Users/damien/.ansible/tmp/ansible-tmp-1486431728.36-240467798124239/ /Users/damien/.ansible/tmp/ansible-tmp-1486431728.36-240467798124239/aos_logical_device.py && sleep 0'
<aos> EXEC /bin/sh -c '/Users/damien/virtualenvs/ansible-dev/bin/python /Users/damien/.ansible/tmp/ansible-tmp-1486431728.36-240467798124239/aos_logical_device.py; rm -rf "/Users/damien/.ansible/tmp/ansible-tmp-1486431728.36-240467798124239/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/folders/vn/2sns6pr17wzdszrwdq79x3th0000gn/T/ansible_BaSnQC/ansible_module_aos_logical_device.py", line 227, in <module>
    main()
  File "/var/folders/vn/2sns6pr17wzdszrwdq79x3th0000gn/T/ansible_BaSnQC/ansible_module_aos_logical_device.py", line 224, in main
    logical_device(module)
  File "/var/folders/vn/2sns6pr17wzdszrwdq79x3th0000gn/T/ansible_BaSnQC/ansible_module_aos_logical_device.py", line 202, in logical_device
    logical_device_absent(module, aos, my_logical_dev)
  File "/var/folders/vn/2sns6pr17wzdszrwdq79x3th0000gn/T/ansible_BaSnQC/ansible_module_aos_logical_device.py", line 142, in logical_device_absent
    my_logical_dev.delete()
  File "/Users/damien/projects/aos-pyez/pylib/apstra/aosom/collection_item.py", line 236, in delete
    got = self.api.requests.delete(self.url)
  File "/Users/damien/virtualenvs/ansible-dev/lib/python2.7/site-packages/requests/sessions.py", line 567, in delete
    return self.request('DELETE', url, **kwargs)
  File "/Users/damien/virtualenvs/ansible-dev/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/damien/virtualenvs/ansible-dev/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/damien/virtualenvs/ansible-dev/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

fatal: [aos]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "aos_logical_device"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/vn/2sns6pr17wzdszrwdq79x3th0000gn/T/ansible_BaSnQC/ansible_module_aos_logical_device.py\", line 227, in <module>\n    main()\n  File \"/var/folders/vn/2sns6pr17wzdszrwdq79x3th0000gn/T/ansible_BaSnQC/ansible_module_aos_logical_device.py\", line 224, in main\n    logical_device(module)\n  File \"/var/folders/vn/2sns6pr17wzdszrwdq79x3th0000gn/T/ansible_BaSnQC/ansible_module_aos_logical_device.py\", line 202, in logical_device\n    logical_device_absent(module, aos, my_logical_dev)\n  File \"/var/folders/vn/2sns6pr17wzdszrwdq79x3th0000gn/T/ansible_BaSnQC/ansible_module_aos_logical_device.py\", line 142, in logical_device_absent\n    my_logical_dev.delete()\n  File \"/Users/damien/projects/aos-pyez/pylib/apstra/aosom/collection_item.py\", line 236, in delete\n    got = self.api.requests.delete(self.url)\n  File \"/Users/damien/virtualenvs/ansible-dev/lib/python2.7/site-packages/requests/sessions.py\", line 567, in delete\n    return self.request('DELETE', url, **kwargs)\n  File \"/Users/damien/virtualenvs/ansible-dev/lib/python2.7/site-packages/requests/sessions.py\", line 488, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/Users/damien/virtualenvs/ansible-dev/lib/python2.7/site-packages/requests/sessions.py\", line 609, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Users/damien/virtualenvs/ansible-dev/lib/python2.7/site-packages/requests/adapters.py\", line 473, in send\n    raise ConnectionError(err, request=request)\nrequests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine(\"''\",))\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

Code for `aos_logical_device`module is here: https://github.com/dgarros/ansible/blob/aos_logical_device/lib/ansible/modules/network/aos/aos_logical_device.py

**Comment by jeremyschulman** [comment]
@dgarros - I suspect this may be a result of https://github.com/Apstra/aos-pyez/issues/47.  I am investigating now.

**Comment by jeremyschulman** [comment]
I took a "shortcut" to prevent a breaking change, by returning the aos.api.requests.headers as the aos.api.headers property.  This results in returning extra information, for example:

````python
>>> aos.api.headers
{'AUTHTOKEN': u'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiY3JlYXRlZF9hdCI6IjIwMTctMDItMDZUMjA6Mzg6MTMuMDA1MTAzWiIsInNlc3Npb24iOiIyZDI5Yzg2NC1lNGRkLTRhYzUtOTY3Ni0zNjk1MzI5MDRlNmEifQ.KopZoT6Fqfq8iU_rel-o6sBgt89knZYN0T7ngIwUn5c', 'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.13.0'}
````

Only the 'AUTHTOKEN' is needed.  I suspect that the extra requests header information is causing this issue. 

To that effect, I am going to rework the "resume session" code within the aos-pyez.  This will result in a small breaking change (I was trying to avoid).  Looking at your code, this change should only affect the `get_aos_session`.  More details to follow once I have something ready for you.

**Comment by jeremyschulman** [comment]
I've changed the way the session information is being returned / resumed; I've created a new aos property called 'session' that can be used to retrieve and restore the session.

It is used as shown on the updated aos-ansible modules here:
https://github.com/Apstra/aos-ansible/tree/breaking_aospyez_060/library

**Comment by jeremyschulman** [comment]
@dgarros - just merged fix into develop branch.  Please "git fetch && git pull" this repo and re-test your ansible modules.  I'll leave this issue open until I hear back.
