### ISSUE TITLE
(Develop /  Cabling) Aos-PyEZ posting unassignable resources

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#88]
Attempting to use slots API - AOS Py-EZ seems to be posting all cabling slot overrides, which may be including nonassignable slots for LAG bonds.

Included is http debug logging as best as I could handle with some details removed.

```
>>> left['blueprint'].cabling.Nodes['arista_leaf1']
{
  "blueprint": "vxlan", 
  "rendered": {
    "spine1<->arista_leaf1": "Ethernet2/1", 
    "spine2<->arista_leaf1": "Ethernet3/1", 
    "arista_leaf1<->arista_leaf2[1]": "Ethernet1/1", 
    "arista_leaf1<->arista_leaf2": "port-channel3", 
    "arista_leaf1<->arista_server2": "port-channel2", 
    "arista_leaf1<->arista_server2[1]": "Ethernet7/2", 
    "arista_leaf1<->arista_server1": "port-channel1", 
    "arista_leaf1<->arista_server1[1]": "Ethernet7/1"
  }, 
  "slot.value": {}, 
  "name": "arista_leaf1", 
  "slot_name": "node_arista_leaf1_interfaces"
}
```

Now, attempting to write:

```
>>> left['blueprint'].cabling.Nodes['arista_leaf1']['spine1<->arista_leaf1'] = 'Ethernet1/1'
send: 'PUT /api/blueprints/50bce08b-7e76-4a98-ae42-b620d498ccc5/slots/node_arista_leaf1_interfaces HTTP/1.1\r\nHost: 172.20.89.3:8888\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.13.0\r\nAUTHTOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiY3JlYXRlZF9hdCI6IjIwMTctMDMtMjFUMDE6MDY6NDguNjU0MTAyWiIsInNlc3Npb24iOiIxMzFhYmNmZi03N2ExLTRhOTktYjY5My1kNmFkYjVlMjkzNWUifQ.spUNmBCzvLSjuR9zcOMPrE-50C_oahUnRzWrupc8ZpA\r\nContent-Length: 379\r\nContent-Type: application/json\r\n\r\n{"spine1<->arista_leaf1": "Ethernet1/1", "spine2<->arista_leaf1": "Ethernet3/1", "arista_leaf1<->arista_leaf2[1]": "Ethernet1/1", "arista_leaf1<->arista_leaf2": "port-channel3", "arista_leaf1<->arista_server2": "port-channel2", "arista_leaf1<->arista_server2[1]": "Ethernet7/2", "arista_leaf1<->arista_server1": "port-channel1", "arista_leaf1<->arista_server1[1]": "Ethernet7/1"}'
reply: 'HTTP/1.1 422 UNPROCESSABLE ENTITY\r\n'
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Date: Tue, 21 Mar 2017 01:12:24 GMT
DEBUG:requests.packages.urllib3.connectionpool:http://172.20.89.3:8888 "PUT /api/blueprints/50bce08b-7e76-4a98-ae42-b620d498ccc5/slots/node_arista_leaf1_interfaces HTTP/1.1" 422 None
Traceback (most recent call last):
  File "/home/jp/pycharm-2016.3.2/helpers/pydev/_pydevd_bundle/pydevd_exec.py", line 3, in Exec
    exec exp in global_vars, local_vars
  File "<input>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/apstra/aosom/blueprint_modules/cabling/cabling.py", line 55, in __setitem__
    self.update({link_name: interface})
  File "build/bdist.linux-x86_64/egg/apstra/aosom/blueprint_modules/cabling/cabling.py", line 104, in update
    self.slot.write(write_back)
  File "build/bdist.linux-x86_64/egg/apstra/aosom/blueprint_modules/slot_params.py", line 75, in write
    resp=got)

SessionRqstError: 422:{"errors": {"arista_leaf1<->arista_server2": ["Unknown resource ID"], "arista_leaf1<->arista_server1": ["Unknown resource ID"], "arista_leaf1<->arista_leaf2": ["Unknown resource ID"]}} - unable to write slot: node_arista_leaf1_interfaces
`````
Noticing that each of the endpoint errors are the port-channel interfaces.  Aos-PyEZ Json post is attempting to post all slots at the same time.

```
{"spine1<->arista_leaf1": "Ethernet1/1", "spine2<->arista_leaf1": "Ethernet3/1", "arista_leaf1<->arista_leaf2[1]": "Ethernet1/1", "arista_leaf1<->arista_leaf2": "port-channel3", "arista_leaf1<->arista_server2": "port-channel2", "arista_leaf1<->arista_server2[1]": "Ethernet7/2", "arista_leaf1<->arista_server1": "port-channel1", "arista_leaf1<->arista_server1[1]": "Ethernet7/1"}
```

Removing the port-channels from the post allows me to override cables if I avoid assigning interfaces that are associated with port-channels.
(manual http request).
```
'{"spine1<->arista_leaf1": "Ethernet1/1", "spine2<->arista_leaf1": "Ethernet3/1", "arista_leaf1<->arista_leaf2[1]": "Ethernet1/1", "arista_leaf1<->arista_server2[1]": "Ethernet7/2", "arista_leaf1<->arista_server1[1]": "Ethernet7/1"}' 
```

So back-end AOS doesn't like us setting slots for port-channel names, but aos-pyez posts all interface names in one blob so I can't separate out individual interfaces.

**Comment by jpsenior** [comment]
Checked AOS 1.1.1-16 Slots API.  Extra interface names are being rendered in cabling extensions.

From GET /blueprints/<bpid>/slots - node_arista_leaf1_interfaces.  noting slot names "arista_leaf1<->arista_leaf2", "arista_leaf1<->arista_server2", and "arista_leaf1<->arista_server1" are not present from AOS, but are showing up in 'rendered' interfaces on aos-pyez.

```
   {
      "slot_type": "STRING",
      "name": "node_arista_leaf1_interfaces",
      "ids": [
        "spine1<->arista_leaf1",
        "arista_leaf1<->arista_server1[1]",
        "arista_leaf1<->arista_leaf2[1]",
        "arista_leaf1<->arista_server2[1]",
        "spine2<->arista_leaf1"
      ]
    },

```

**Comment by jpsenior** [comment]
I patched this locally on my install because it was blocking some work I was doing - essentially instead of self.rendered, i was using self.slots.value() or something similar.

**Comment by jeremyschulman** [comment]
@jpsenior - given the change for AOS 1.2, I would like to defer on this reported issue.  We can test/validate that the cabling aspects are fully functional in the new release.

**Comment by jeremyschulman** [comment]
closing, will re-visit for 2.0 release.
